### ISSUE TITLE
怎么安装  看到github上的代码发现是使用大量正则去做的 和论文上面写的有些许出入，这个是什么原因？

### ISSUE THREAD

**Issue by python-D** [kingname/GeneralNewsExtractor#1]

**Comment by kingname** [comment]
你好，论文对应的是正文的提取。所以ContentExtractor.py里面才是论文中对应的正文提取。
剩下的时间、作者是我使用正则实现的。

安装方法非常简单。

1. 把代码下载到本地
2. 进入代码的根文件夹
3. 你的Python需要首先安装pipenv这个包管理器
4. 执行命令`pipenv install`
5. 执行命令`pipenv shell`
6. 执行`python3 GeneralNewsExtractor.py`

**Comment by python-D** [comment]
感谢大佬 指点 我去 学习下 ，下次面试吹牛逼 可以捎带这个了 


------------------ 原始邮件 ------------------
发件人: "kingname"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 上午10:54
收件人: "kingname/GeneralNewsExtractor"<GeneralNewsExtractor@noreply.github.com>;
抄送: "王佳康"<2897443340@QQ.COM>;"Author"<author@noreply.github.com>;
主题: Re: [kingname/GeneralNewsExtractor] 怎么安装  看到github上的代码发现是使用大量正则去做的 和论文上面写的有些许出入，这个是什么原因？ (#1)




你好，论文对应的是正文的提取。所以ContentExtractor.py里面才是论文中对应的正文提取。
 剩下的时间、作者是我使用正则实现的。
 
安装方法非常简单。
  
把代码下载到本地
 
进入代码的根文件夹
 
你的Python需要首先安装pipenv这个包管理器
 
执行命令pipenv install
 
执行命令pipenv shell
 
执行python3 GeneralNewsExtractor.py
