### ISSUE TITLE
 个别标题无法解析

### ISSUE THREAD

**Issue by liangbaika** [kingname/GeneralNewsExtractor#101]
文章地址  http://fzggw.zj.gov.cn/art/2016/11/22/art_1621004_30332664.html
 这种(1-10月德清县固定资产投资结构趋稳趋优)标题带  - 无法解析  只能取到1 , -后面的无法取到

**Comment by kingname** [comment]
感谢反馈

**Comment by liangbaika** [comment]
大概啥时候能更新啊 项目里在用 目前我这边特殊处理了下 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;kingname&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月21日(星期一) 下午2:07
收件人:&nbsp;&quot;kingname/GeneralNewsExtractor&quot;<GeneralNewsExtractor@noreply.github.com&gt;;
抄送:&nbsp;&quot;凉白开&quot;<1144388620@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kingname/GeneralNewsExtractor]  个别标题无法解析 (#101)

**Comment by kingname** [comment]
fixed: https://github.com/kingname/GeneralNewsExtractor/pull/102

请更新0.2.5版本。
