### ISSUE TITLE
有的标题只能获取到一个字

### ISSUE THREAD

**Issue by shanliangLS** [kingname/GeneralNewsExtractor#106]
**bug的现象**

1. 你期望的返回是？
天宫一号与神舟九号载人交会对接任务第二场新闻发布会

2. 实际GNE给你的返回是？
接

**如何复现**

1. 目标网址
http://www.cmse.gov.cn/ztbd/xwfbh/201206/t20120624_43188.html

2. 你怎么调用GNE的
``` python
import json
from gne import GeneralNewsExtractor

def htmlGneJson(html, name):
    extractor = GeneralNewsExtractor()
    result = extractor.extract(html)
    print(result['content'])
    result = json.dumps(result, ensure_ascii=False, indent=4, separators=(',', ':'))
    print(result)
    with open('../result/'+name+'.json', 'w', encoding='UTF-8') as fw:
        fw.write(result)

if __name__ == '__main__':
    with open('../outerhtml/example.html', encoding='UTF-8') as f:
        html = f.read()
    htmlGneJson(html, 'example')
```

**屏幕截图**
![image](https://user-images.githubusercontent.com/40483715/107871133-d8408e00-6ed9-11eb-9b10-e9f082176360.png)
![image](https://user-images.githubusercontent.com/40483715/107871141-f27a6c00-6ed9-11eb-8b38-487252d09b12.png)
![image](https://user-images.githubusercontent.com/40483715/107871154-1473ee80-6eda-11eb-86ed-7bb051757a65.png)
![image](https://user-images.githubusercontent.com/40483715/107871170-37060780-6eda-11eb-8019-db6e9ae7e56a.png)

**使用环境:**
 - OS: [ Windows 10 ]
 - Python版本 [ Python 3.6.10 :: Anaconda, Inc. ]
 - GNE版本 [ 0.2.5 ]

**Comment by kingname** [comment]
由于你爬的是同一个网站，建议增加一个参数： title_xpath，直接指定到标题的 Xpath。

**Comment by kingname** [comment]
在没有设定这个参数的情况下，为什么会出现标题只有一个字的情况，我明天看一下

**Comment by kingname** [comment]
fixed：https://github.com/kingname/GeneralNewsExtractor/pull/107
请更新GNE 0.2.6版本。
