### ISSUE TITLE
因把script节点删除导致把发布时间的文本给删除了

### ISSUE THREAD

**Issue by meichuanneiku** [kingname/GeneralNewsExtractor#11]
在gne\utils.py\normalize_node(element: HtmlElement)中删除USELESS_TAG列表中的节点时，会把发布时间文本删除掉
把USELESS_TAG中'script'去掉之后，正文抓取又不对
原始地址：http://www.sxmu.edu.cn/jijian/info/1009/1081.htm
![image](https://user-images.githubusercontent.com/8164375/65230595-b71b1880-db00-11e9-9a29-d99405605b2c.png)

**Comment by kingname** [comment]
代码里面只会删除 script标签及其内部的代码，你在 issue 截图中的
>来源：
>   | 发布时间： 2018-05-17 | 浏览次数：

不属于 script 标签内部的内容，并不会被删除。

**Comment by kingname** [comment]
这里时间提取到正文中的时间，而不是真正的发布时间，是由于正则表达式的问题。

**Comment by meichuanneiku** [comment]
在GeneralNewsExtractor-master\gne\__init__.py中添加在删除无用标签的文本打印
![image](https://user-images.githubusercontent.com/8164375/65398196-736a2c80-dde8-11e9-80eb-50bcdb6cc191.png)
下图的文本信息就没有了
![image](https://user-images.githubusercontent.com/8164375/65398211-87ae2980-dde8-11e9-99ae-d7a799f98ee9.png)
