### ISSUE TITLE
爬取交易所新闻失败

### ISSUE THREAD

**Issue by nickhuangxinyu** [kingname/GeneralNewsExtractor#112]
**bug的现象**
空内容

1. 你期望的返回是？
新闻内容
2. 实际GNE给你的返回是？
空内容

**如何复现**

1. 目标网址 http://www.shfe.com.cn//news/notice/911324675.html
2. 你怎么调用GNE的
```
from gne import GeneralNewsExtractor

extractor = GeneralNewsExtractor()
html = 'http://www.shfe.com.cn//news/notice/911324675.html'
result = extractor.extract(html)
print(result)
```

![image](https://user-images.githubusercontent.com/29453090/118383440-38a5af80-b630-11eb-8ab8-448ea5c7c422.png)

**Comment by kingname** [comment]
请注意阅读文档。GNE 不含主动请求网站的功能。html 对应的应该是网站经过渲染的源代码。
