### ISSUE TITLE
新闻正文内容获取不全且标题错误

### ISSUE THREAD

**Issue by lv2020** [kingname/GeneralNewsExtractor#12]
具体网页是这个：http://www.gsc.org.cn/content.aspx?id=1004
出现的问题是内容只获取到了中间的一段，而标题则是错误的

**Comment by kingname** [comment]
标题问题已经修复。

**Comment by kingname** [comment]
#13 
fixed.

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/65383884-ee323980-dd4d-11e9-966e-d5b6dec4d619.png)
