### ISSUE TITLE
百家号内容提不出来

### ISSUE THREAD

**Issue by Left-Hai** [kingname/GeneralNewsExtractor#19]
https://baijiahao.baidu.com/s?id=1594379932298080127&wfr=spider&for=pc
正文都在html里
识别内容为
{'title': '这款休闲裤太帅了，让你时尚潮流穿着舒适', 'author': '', 'publish_time': '18-03-0823:16', 'content': '百度首页\n登录\n个人中心\n帐号设置\n意见反馈\n退出'}

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/65570019-4c4f5e80-df92-11e9-8218-8d3f54b34e66.png)

一切正常，应该是你的使用方法不对。
