### ISSUE TITLE
content提取错误

### ISSUE THREAD

**Issue by jueshiyizhimao** [kingname/GeneralNewsExtractor#21]
3篇文章的链接：
http://www.zsnews.cn/zsdongqu/index/view/cateid/337/id/607671.html
http://www.79tao.com/thread-889817-1-1.html
https://finance.qq.com/a/20190923/000843.htm
不确定是不是我环境的问题
![image](https://user-images.githubusercontent.com/26734950/65586481-d27d9c00-dfb6-11e9-9f33-0cb095c2b2c1.png)

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/65809644-054fac00-e1d2-11e9-9ce2-f4a1183d1402.png)
中山网一切正常。

**Comment by kingname** [comment]
79tao 是论坛，本工具暂不支持论坛提取。

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/65809703-f0bfe380-e1d2-11e9-8ad9-3130999b014f.png)
腾讯财经：
