### ISSUE TITLE
作者没有提取出来

### ISSUE THREAD

**Issue by jueshiyizhimao** [kingname/GeneralNewsExtractor#22]
新闻链接：https://www.csdn.net/article/2014-08-24/2821349-KnownSec-KconV3

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/65809829-6d06f680-e1d4-11e9-8d4c-c603c9727e20.png)
这种情况有点麻烦。我得想想。

**Comment by kingname** [comment]
最简单的办法就是自己直接指定 xpath

**Comment by zhu733756** [comment]
//span[@class="ago"]/text()  众口难调，还不如指定xpath作为修正点来弥补不足

**Comment by kingname** [comment]
新版本 GNE 已经支持指定 XPath 定向提取标题了。
