### ISSUE TITLE
人民网部分网页提取不到正文

### ISSUE THREAD

**Issue by python-D** [kingname/GeneralNewsExtractor#24]
{'type': '文化', 'url': 'http://culture.people.com.cn/n1/2019/0615/c1013-31153719.html', 'data': '{\n  "title": "女儿出嫁，郑板桥画了几笔兰花当嫁妆",\n  "author": "汤诗瑶",\n  "publish_time": "2019年06月15日08:18",\n  "content": "人 民 网 版 权 所 有 ，未 经 书 面 授 权 禁 止 使 用\\nCopyright © 1997-2019 by www.people.com.cn. all rights reserved"\n}'}

**Comment by kingname** [comment]
#26
