### ISSUE TITLE
百家号提取content字段不正确

### ISSUE THREAD

**Issue by siryang2006** [kingname/GeneralNewsExtractor#29]
http://baijiahao.baidu.com/s?id=1646796218135408573&wfr=spider&for=pc
http://baijiahao.baidu.com/s?id=1646116705759028486&wfr=spider&for=pc
http://baijiahao.baidu.com/s?id=1646397256193648043&wfr=spider&for=pc
http://baijiahao.baidu.com/s?id=1646299231611696619&wfr=spider&for=pc

比如：
http://baijiahao.baidu.com/s?id=1646116705759028486&wfr=spider&for=pc
提取出来是{'title': '日本最后一家传呼机公司停止服务，殡仪馆为BB机送终', 'publish_time': '9月30日', 'author': '', 'content': '百度首页\n登录\n个人中心\n帐号设置\n意见反馈\n退出'} 这种

**Comment by kingname** [comment]
感谢反馈

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/71558182-513d1600-2a8b-11ea-8c43-58dd15fbcf83.png)

![image](https://user-images.githubusercontent.com/5440523/71558204-85b0d200-2a8b-11ea-84c7-7b964454e0a1.png)

一切正常，可以正常提取
