### ISSUE TITLE
多个作者用  、连接无法提取

### ISSUE THREAD

**Issue by zhu733756** [kingname/GeneralNewsExtractor#34]
PATTERN = [
        '(作者[：|:| |丨|/]\s*[\u4E00-\u9FA5a-zA-Z、 ]{2,20})[）】\)\]]?[^\u4E00-\u9FA5|:|：]',
        '(记者[：|:| |丨|/]\s*[\u4E00-\u9FA5a-zA-Z、 ]{2,20})[）】\)\]]?[^\u4E00-\u9FA5|:|：]',
        '(原创[：|:| |丨|/]\s*[\u4E00-\u9FA5a-zA-Z、 ]{2,20})[）】\)\]]?[^\u4E00-\u9FA5|:|：]',
        '(撰文[：|:| |丨|/]\s*[\u4E00-\u9FA5a-zA-Z、 ]{2,20})[）】\)\]]?[^\u4E00-\u9FA5|:|：]',
        '(文/图[：|:| |丨|/]?\s*[\u4E00-\u9FA5a-zA-Z、 ]{2,20})[）】\)\]]?[^\u4E00-\u9FA5|:|：]',
        ]

**Comment by zhu733756** [comment]
标题写错了 应该是 提取不全

**Comment by kingname** [comment]
目前是有这个问题，

**Comment by kingname** [comment]
现在最新版本的 GNE 已经执行通过输入 XPath 定向提取标题了。更新试一试。

**Comment by kingname** [comment]
希望你能提供几篇适用于这几个 正则表达式的网页例子，以便进一步测试并添加到 GNE 中。感谢。
