### ISSUE TITLE
部分不可见的节点也被解析了出来

### ISSUE THREAD

**Issue by kbaicai** [kingname/GeneralNewsExtractor#38]
比如说这个：http://www.njxfhn.com/post/2740.html

**Comment by kingname** [comment]
感谢，我去看一看

**Comment by kbaicai** [comment]
补充一下，你可以查看源代码，搜索这个 <div style="display:none">  这个块的东西全是垃圾来的。

**Comment by kingname** [comment]
好的。

**Comment by kingname** [comment]
这种情况下，你在调用 extract 方法的时候，传入`noise_node_list`即可：

![image](https://user-images.githubusercontent.com/5440523/69489357-03dcf000-0eb2-11ea-824f-2805373b39fe.png)

**Comment by kingname** [comment]
https://github.com/kingname/GeneralNewsExtractor/commit/c2be936168bc55bc34fddc4a6b1916adf984f4da
