### ISSUE TITLE
content提取内容重复

### ISSUE THREAD

**Issue by Mr-iFan** [kingname/GeneralNewsExtractor#39]
在提取多个网页内容时，会出现提取的内容重复，猜测可能存在缓存问题

**Comment by kingname** [comment]
是的。本周末会解决这个问题。

**Comment by kingname** [comment]
请看 example.py 中的这个示例代码：https://github.com/kingname/GeneralNewsExtractor/blob/59cac9df375b015d5daa6e6a5c203e8297328a34/example.py#L11

在处理每一篇 HTML 的时候，都需要重新初始化一个实例。

**Comment by kingname** [comment]
修复。https://github.com/kingname/GeneralNewsExtractor/commit/37caf8d3ed988f853101d93438b02c331e57089e

**Comment by Mr-iFan** [comment]
不可行，而且我还del了变量，还是会出现重复的问题，当重复的数据出现时，后面的好几个解析都是重复的。

**Comment by kingname** [comment]
请更新最新版程序，问题已经解决。
