### ISSUE TITLE
抽取新华网正文不正确

### ISSUE THREAD

**Issue by JingqiongWang** [kingname/GeneralNewsExtractor#50]
抽取新华网正文不正确， url=“http://www.xinhuanet.com/world/2019-12/10/c_1125327450.htm”

**Comment by kingname** [comment]
正文正常提取，反倒是 title 提取不正常。

![image](https://user-images.githubusercontent.com/5440523/71558093-33bb7c80-2a8a-11ea-87b7-efe96c4fbf52.png)
