### ISSUE TITLE
有些页面图片不能识别

### ISSUE THREAD

**Issue by ego008** [kingname/GeneralNewsExtractor#52]
如这个页面 https://3w.huanqiu.com/a/64d6f1/9CaKrnKolBA?agt=8

与凤凰网一样的内容 #47  

```
<p><img src="xxxx" alt="" ></p>
```

把内容放到 `https://news.ifeng.com/c/7rtKNyg6PU9` 正文里能识别。

**Comment by kingname** [comment]
这个几乎没有文字，GNE是根据文字与标签的比例来寻找正文的，https://3w.huanqiu.com/a/64d6f1/9CaKrnKolBA?agt=8这个文章的文字太少了，GNE没有办法定位到图片所在的区域，就导致了图片无法正常抓取。
