### ISSUE TITLE
[Bug report] 澎湃新闻提取只有一小段

### ISSUE THREAD

**Issue by TTTPOB** [kingname/GeneralNewsExtractor#57]
**bug的现象**

1. 你期望的返回是？
正确提取澎湃新闻的正文内容
2. 实际GNE给你的返回是？
只有一小段正文内容被提取出来
据我观察似乎是图注和小标题对提取的影响比较大
**如何复现**

1. 目标网址
https://www.thepaper.cn/newsDetail_forward_5420361
2. 你怎么调用GNE的
```python
extractor = GeneralNewsExtractor()
extractor.extract(theHtmlString)
```
**屏幕截图**
![图片](https://user-images.githubusercontent.com/19909103/71757781-9b7f2680-2ed3-11ea-8a2b-8f038d5b666b.png)
![图片](https://user-images.githubusercontent.com/19909103/71757786-a76ae880-2ed3-11ea-81ce-9fa1dd45cbac.png)

**使用环境:**
 - OS: [e.g. Ubuntu 19.04/Windows 10/macOS ]
Arch Linux on WIndows 10 (WSL)
 - Python版本 [e.g. 3.7.1]
3.8.1
 - GNE版本 [e.g. 0.1.4]
0.1.4

**Comment by kingname** [comment]
收到。

**Comment by kingname** [comment]
fixed https://github.com/kingname/GeneralNewsExtractor/commit/e7f4056caf87cc274a77fca6c72e29c7c6eeaf74
