### ISSUE TITLE
百家号文章正文提取不到

### ISSUE THREAD

**Issue by dedegs** [kingname/GeneralNewsExtractor#58]
**bug的现象**
百家号文章html源代码当天中正文内容，正文提取不到

1. 你期望的返回是？
正文内容
2. 实际GNE给你的返回是？
'content': '百度首页\n登录\n个人中心\n帐号设置\n意见反馈\n退出'
**如何复现**

1. 目标网址
https://baijiahao.baidu.com/s?id=1655696407716538005
2. 你怎么调用GNE的
url = 'https://baijiahao.baidu.com/s?id=1655696407716538005'
html = requests.get(url,headers,timeout=50).content.decode('utf-8')
print(html)
extractor = GeneralNewsExtractor()
result = extractor.extract(html)

**使用环境:**
 - OS: [Windows 10]
 - Python版本 [e.g. 3.7.1]
 - GNE版本 [e.g. 0.1.4]

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/75608202-77893b80-5b38-11ea-8fb1-f45fba665d43.png)


最新版 GNE 完美适配。
