### ISSUE TITLE
对那个论文有个疑问 关于符合密度

### ISSUE THREAD

**Issue by Rockyzsu** [kingname/GeneralNewsExtractor#6]
根据论文的公式：
                Ti - LTi
        SbDi = --------------
                 Sbi + 1

        SbDi: 符号密度
        Sbi：符号数量

如果一个节点里面的文本的符号出现次数越多，符号密度SbDi的值就越小，但是文档里说会越大，如何解 ？

**Comment by kingname** [comment]
因为它这里考虑的是一个『合乎逻辑』的正文。而不是为了欺骗这个程序而特意构造的文本。在一篇正常的文章中，文章越长，标点符号就阅读，这是自然而然的情况。

而你可能以为，会不会有一篇新闻，里面某一个栏目没有汉字，直接写了几百个标点符号。这种情况当然可以欺骗这个程序，但是那属于『特意构造』出来的bad case。

**Comment by kingname** [comment]
在一篇正常的文章中，标点符号越多，那么正文的文字也就越多。分子分母同时增加。而显然，文字增长会比标点符号增长快，所以这个比值会变大。

**Comment by Rockyzsu** [comment]
closed.
