### ISSUE TITLE
提取正文异常

### ISSUE THREAD

**Issue by python-D** [kingname/GeneralNewsExtractor#60]
**bug的现象**
{'title': '5月20日至31日，京沪高速无锡至江阴大桥至广陵枢纽段封闭！', 'author': '无锡交警', 'publish_time': '5月20日', 'content': '特别声明：以上内容(如有图片或视频亦包括在内)为自媒体平台“网易号”用户上传并发布，本平台仅提供信息存储服务。\nNotice: The content above (including the pictures and videos if any) is uploaded and posted by a user of NetEase Hao, which is a social media platform and only provides information storage services.', 'images': []}

1. 目标网址  http://dy.163.com/v2/article/detail/EFDAIN1E054550F0.html
2. 你怎么调用GNE的
import requests
from gne import GeneralNewsExtractor

url = 'http://dy.163.com/v2/article/detail/EFDAIN1E054550F0.html'
r = requests.get(url)
r.encoding = 'gbk'
extractor = GeneralNewsExtractor()
auto_result = extractor.extract(r.text)
print(auto_result)
**屏幕截图**

**使用环境:**
 - OS: [e.g. Ubuntu 19.04/Windows 10/macOS ]
 - Python版本 [e.g. 3.7.1]
 - GNE版本 [e.g. 0.1.4]

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/75607953-41e35300-5b36-11ea-96fe-ababc6cb4997.png)
请在 `noise_node_list`参数列表中加上：`//div[@class="statement"]`即可解决问题。
