### ISSUE TITLE
gne提取36kr新闻无法获取title

### ISSUE THREAD

**Issue by rottengeek** [kingname/GeneralNewsExtractor#61]
**bug的现象**

1. 你期望的返回是？
2. 实际GNE给你的返回是？

**如何复现**

1. 目标网址 
https://36kr.com/p/5288922
2. 你怎么调用GNE的
import requests
from gne import GeneralNewsExtractor
resp = requests.get(url, headers=headers)
extractor = GeneralNewsExtractor()
result = extractor.extract(resp.text)
print(result)
**屏幕截图**
![image](https://user-images.githubusercontent.com/38384303/74311952-956e4680-4dab-11ea-821a-c5aa37d6bf9f.png)

**使用环境:**
 - OS: [e.g. Ubuntu 19.04/Windows 10/macOS ]
 - Python版本 [e.g. 3.7.1]
 - GNE版本 [e.g. 0.1.4]

**Comment by tangyibo** [comment]
可以试试：https://gitee.com/inrgihc/libnpce

**Comment by baby5** [comment]
对于36kr，把这个参数[TITLE_SPLIT_CHAR_PATTERN](https://github.com/kingname/GeneralNewsExtractor/blob/master/gne/defaults.py#L47)改成`[-_]`

**Comment by kingname** [comment]
> 对于36kr，把这个参数[TITLE_SPLIT_CHAR_PATTERN](https://github.com/kingname/GeneralNewsExtractor/blob/master/gne/defaults.py#L47)改成`[-_]`
> 
> 通用信息提取适用大部分情况，对于特例，需要用户自己维护一个规则表。考虑到网站改版的频率不高，这是可行的方案。
> 
> 也可以参考gfwlist的做法，开源一个gnelist，一起贡献规则，一起分享。

感谢你的意见，非常有意义！！

**Comment by kingname** [comment]
@rottengeek 现在 GNE 最新版本已经支持直接指定 Title 的 XPath 从而实现定向提取标题
