### ISSUE TITLE
提取图片链接 可以保存在原来位置吗

### ISSUE THREAD

**Issue by JQ-K** [kingname/GeneralNewsExtractor#67]
如题

**Comment by kingname** [comment]
请看一下有一个参数 `with_body_html`，可以给你保留正文所在的 html 代码。

但如果你想实现：

```
正文正文正文正文正文
正文http://xxx.com/123.png 正文正文
正文正文正文正文
http://xxx.com/456.jpg 正文正文
正文
```

这种形式，目前暂时不支持。

**Comment by JQ-K** [comment]
> 请看一下有一个参数 `with_body_html`，可以给你保留正文所在的 html 代码。
> 
> 但如果你想实现：
> 
> ```
> 正文正文正文正文正文
> 正文http://xxx.com/123.png 正文正文
> 正文正文正文正文
> http://xxx.com/456.jpg 正文正文
> 正文
> ```
> 
> 这种形式，目前暂时不支持。

好的谢谢
