### ISSUE TITLE
新浪科技 无法正常获取正文

### ISSUE THREAD

**Issue by songhao8080** [kingname/GeneralNewsExtractor#7]
```
# http://tech.sina.com.cn/t/2019-09-11/doc-iicezzrq4972166.shtml
from pprint import pprint

from gne import GeneralNewsExtractor
html = """ html 正文"""
extractor = GeneralNewsExtractor()
result = extractor.extract(html)
pprint(result)

```
![image](https://user-images.githubusercontent.com/10607039/64663394-34e68080-d47e-11e9-869c-082b4e3f77c7.png)

**Comment by kingname** [comment]
原因已经找到，是由于正文部分的内部标签（公司中的 tgi）太多，导致内容密度被稀释。

**Comment by kingname** [comment]
fixed
#13 

![image](https://user-images.githubusercontent.com/5440523/65384068-7285bc00-dd50-11e9-8e87-52633350165f.png)
