### ISSUE TITLE
关于标准差的作用calc_standard_deviation

### ISSUE THREAD

**Issue by hwg119** [kingname/GeneralNewsExtractor#70]
作者您好，
标准差是根据所有节点的密码算得的。而在计算每个节点的分数时，都要与之相乘，对每个节点来说该值都是一样的固定值，除了会影响每个节点的分数，并不会对最终的分数排名产生影响，是不是我的理解有问题？

**Comment by kingname** [comment]
你好，你的理解没有问题。确实这个标准差对于选择节点没有帮助。只是在画图的时候让图像之间的差距放大而已。
