### ISSUE TITLE
提取Title的新思路

### ISSUE THREAD

**Issue by kingname** [kingname/GeneralNewsExtractor#72]
从h1-h5中提取文字，然后与<title>标签中的文字对比。如果是子集且较长，一般就是新闻标题。

感谢 @止水 提的建议

**Comment by asyncins** [comment]
我上次说给 GNE 的标题提取提一个 Issues，其实跟 @止水 的思路是相近的。

假设有如下标题：“非常手记：从咖啡厅到云端|不一样的采访一样的Kingname-金刚葫芦网”。按照现有逻辑，标题会切分为“非常手记：从咖啡厅到云端”、“不一样的采访一样的Kingname”和"金刚葫芦网"三段，现有逻辑默认取下标为 0 的那一段，即“非常手记：从咖啡厅到云端”。这样的情况我在实际测试中遇到过很多次，于是稍稍改动了取标题的逻辑：

- 先分割；
- 判断分割后的长度是否大于 2；
- 如果长度不大于 2，则对分割的标题中较短的那一段进行关键词（例如“网”、“新闻”等）筛查，从而得出较长的那段；
- 如果长度大于 2，则进行多段拼接，拼接结果如“非常手记：从咖啡厅到云端”、“非常手记：从咖啡厅到云端 不一样的采访一样的Kingname”、“不一样的采访一样的Kingname 金刚葫芦网”；
- 无论长度是否大于 2，最后都需要进行相似度校验。取正文中 h1~h5 标签包裹的文字，循环与拼接结果进行相似度比较，取相似度最高的作为标题。
- 最后得到的结果大概率为“非常手记：从咖啡厅到云端 不一样的采访一样的Kingname”，如果追求精细化，可以记录分割时的分隔符，在拼接时带上分割符，以求得到更准确的标题。

备注：其他逻辑，例如标题长度阈值等不在此话题讨论范围内；

相似度比较方面，我在代码里采用的是 Python 的 difflib，取 ratio 值。

**Comment by kingname** [comment]
https://github.com/kingname/GeneralNewsExtractor/pull/80
