### ISSUE TITLE
标题抽取逻辑应当调整

### ISSUE THREAD

**Issue by asyncins** [kingname/GeneralNewsExtractor#73]
**bug的现象**

1. 你期望的返回是？
完整标题，例如：本赛季暂停 斯波：联盟做出了正确举措
2. 实际GNE给你的返回是？
网站Title：NBA资讯速看网

**如何复现**

1. 目标网址
答：不用网址，上面的举例可以说明情况
2. 你怎么调用GNE的
答：按照文档调用

**屏幕截图**
![](http://can.sfhfpc.com/sfhfpc/20200312225750.jpg)

补充：不用在意截图的细节，其实上面的举例也可以说明情况

**使用环境:**
 - OS: [macOS ]
 - Python版本 [e.g. 3.6]
 - GNE版本 [忘记了]

建议：调整标题抽取规则顺序，TitleExtractor 中的 extract_by_title 方法优先级不应该是最高的，可以考虑 extract_by_htag 或者 extract_by_xpath。当用户传入 title_xpath 时 extract_by_xpath 的优先级应该最高，反之则 extract_by_htag 最高，例如
```
title = self.extract_by_xpath(element, title_xpath) or self.extract_by_htag(element)  or self.extract_by_title(element)

```

**Comment by kingname** [comment]
感谢。

准备按照#72 所述的方法来进行修改。

**Comment by kingname** [comment]
duplicate of #72

**Comment by kingname** [comment]
Duplicate of #72

**Comment by kingname** [comment]
https://github.com/kingname/GeneralNewsExtractor/pull/80
