### ISSUE TITLE
关于你提到的这篇论文

### ISSUE THREAD

**Issue by chrislinan** [kingname/GeneralNewsExtractor#77]
天下文章一大抄，没想到现在抄的这么明目张胆，你看的论文中写的算法，最早是由哈尔滨工业大学社会计算与 信息检索研究中心的陈鑫在2009年提出的，这篇2019年武汉的论文里他改了个标题，内容上甚至连程序流程图都和2009年陈鑫的文章中的一模一样（另外这种画法不是严格意义上的流程图，学过软件工程的人都知道流程图长啥样）另外，关于这种算法的实现已经有无数人做过同样的事情。
![image](https://user-images.githubusercontent.com/12604912/77521507-c5862a80-6ebd-11ea-9997-ddb297642e98.png)

**Comment by kingname** [comment]
可怕

**Comment by kingname** [comment]
不过现在我在这个论文的基础上已经做过很多定制化的修改了。它在GNE里面的占比应该已经下降到50%了。不过你为什么要把这个当做一个bug提上来。

**Comment by 46319943** [comment]
可怕...我还以为那篇论文是什么新的研究成果。当时刚star这个项目的时候，我马上就把论文下载下来了。
star之后一直没用，过了一段时间要用这个，发现越变越牛逼了！！！
（有人知道 怎么看 自己是什么时候star某个项目的嘛?
