### ISSUE TITLE
对中有插入图片的正文 只提取第一段 

### ISSUE THREAD

**Issue by meichuanneiku** [kingname/GeneralNewsExtractor#9]
python3.7
win7 64

原始地址：http://www.shanxi.gov.cn/yw/sxyw/201909/t20190918_693227.shtml
使用gne对中有插入图片的正文 只提取第一段

![image](https://user-images.githubusercontent.com/8164375/65105233-da619d00-da06-11e9-88c6-90503697e6c4.png)
![image](https://user-images.githubusercontent.com/8164375/65105252-e9e0e600-da06-11e9-8135-4623b2b1dfe4.png)

**Comment by kingname** [comment]
问题的原因在于，新闻正文出现在`div`标签中，而不是`p`标签中。

**Comment by meichuanneiku** [comment]
搞定，需设置提取的正文的标签

**Comment by kingname** [comment]
现在已经不需要设置提取正文的标签了

![image](https://user-images.githubusercontent.com/5440523/65384539-0b6b0600-dd56-11e9-93f6-61a8cafb7374.png)
