### ISSUE TITLE
正文指定 body_xpath 后无法提取

### ISSUE THREAD

**Issue by cjr0707** [kingname/GeneralNewsExtractor#91]
**bug的现象**

原文链接(base64)：aHR0cCUzQS8vd3d3Lmd1aXpob3UuZ292LmNuL3p3Z2svemNmZy9zemZ3al84MTkxL3FmYmZfODE5Ni8yMDE3MDkvdDIwMTcwOTI1XzgyMzE3My5odG1s

指定body_xpath="//div[@class='zw-con']"后，报错下标越界，就是没找到它，感觉和其中的text标签有关，麻烦青南哥看看啦。

**Comment by kingname** [comment]
收到。我看看

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/95220836-72f0d800-0829-11eb-8466-c3effe88004f.png)

经过测试，没有任何问题，可以正确提取。请看看你的GNE 版本是否有问题。更新到最新版0.2.4试一试。

**Comment by cjr0707** [comment]
抱歉了，当时看错了，我这边使用的是它没有渲染好的html，`<div class="zw-con">`，直接包含了其正文内容，这种直接 指定包含正文所有内容的xpath，目前是无法使用gne直接提取的吗？

**Comment by kingname** [comment]
直接指定 `body_xpath="//div[@class="zw-con"]"`是可以的。你看我截图里面就是这样指定的。

**Comment by cjr0707** [comment]
我简单复现一下，如下代码，因为使用的是未渲染好的html，所以`//div[@class="zw-con"]`中直接是一连串正文

```python
from gne import GeneralNewsExtractor

html = '''<li><div class="zw-con">这是正文</div></li>'''
extractor = GeneralNewsExtractor()
result = extractor.extract(html, body_xpath="//div[@class='zw-con']")
print(result)
```
此时会报错`IndexError: list index out of range`，这样的情况算是bug？

而如果我将`html = '''<li><div class="zw-con"><text>这是正文</text>这个在div下</div></li>'''`更改为这样，则应该是您测试的html，可以正常提取。

**Comment by kingname** [comment]
你需要看看未经渲染的HTML里面，是不是真的有//div[@class='zw-con'] 这个div标签。如果没有的话，自然就会报错。另外，GNE只能处理经过渲染的页面源代码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CJR妙传C罗戏耍西西"<notifications@github.com&gt;; 
发送时间: 2020年10月9日(星期五) 上午10:39
收件人: "kingname/GeneralNewsExtractor"<GeneralNewsExtractor@noreply.github.com&gt;; 
抄送: "kingname"<greensouth@foxmail.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [kingname/GeneralNewsExtractor] 正文指定 body_xpath 后无法提取 (#91)





 
我简单复现一下，如下代码，因为使用的是未渲染好的html，所以//div[@class="zw-con"]中直接是一连串正文
 from gne import GeneralNewsExtractor html = '''<li&gt;<div class="zw-con"&gt;这是正文</div&gt;</li&gt;''' extractor = GeneralNewsExtractor() result = extractor.extract(html, body_xpath="//div[@class='zw-con']") print(result)
 
此时会报错IndexError: list index out of range，这样的情况算是bug？
 
而如果我将html = '''<li&gt;<div class="zw-con"&gt;<text&gt;这是正文</text&gt;这个在div下</div&gt;</li&gt;'''更改为这样，则应该是您测试的html，可以正常提取。
