### ISSUE TITLE
从0.1.8版本更新到0.2.3版本后，新闻正文提取出错

### ISSUE THREAD

**Issue by 46319943** [kingname/GeneralNewsExtractor#92]
**bug的现象**

1. 你期望的返回是？
提取到新闻正文

2. 实际GNE给你的返回是？
提取到网站底部网站信息

**如何复现**

1. 目标网址
http://news.cjn.cn/sywh/202010/t3714581.htm?spm=zm1066-001.0.0.1.eBS4u1

2. 你怎么调用GNE的
```
cls.extractor.extract(
            text,
            with_body_html=True,
            host=url,
)
```

**屏幕截图**
0.1.8版本提取内容，正常提取到了新闻正文：
![image](https://user-images.githubusercontent.com/17161318/95084819-fdb1d400-0750-11eb-8fdc-54ab25575e8e.png)

0.2.3版本提取内容，只提取到了网站底部文本：
![image](https://user-images.githubusercontent.com/17161318/95084730-d9ee8e00-0750-11eb-9d84-b97bd8d2e679.png)

网站底部：
![image](https://user-images.githubusercontent.com/17161318/95085070-4d909b00-0751-11eb-8830-b67ea3259426.png)

**使用环境:**
 - OS: Ubuntu 16.04, Windows 10
 - Python版本: Python3.7.6, Python3.8.3
 - GNE版本 0.1.8, 0.2.3

**Comment by kingname** [comment]
感谢，确实是一个问题，我去看看

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/95213820-cd863600-0821-11eb-960f-06bffb66ddf4.png)

**Comment by kingname** [comment]
fixed https://github.com/kingname/GeneralNewsExtractor/pull/93
