### ISSUE TITLE
提取的正文值异常， 有正文外的大量字符

### ISSUE THREAD

**Issue by shishiwie** [kingname/GeneralNewsExtractor#96]
**bug的现象**

1. 你期望的返回是？
正文
2. 实际GNE给你的返回是？
正文+多余字符串

**如何复现**

1. 目标网址 
https://www.mct.gov.cn/whzx/whyw/202009/t20200921_875251.htm
2. 你怎么调用GNE的
正常调用

**屏幕截图**

**使用环境:**
 - OS: [e.g. Ubuntu 19.04/Windows 10/macOS ]
 - Python版本 [e.g. 3.7.1]
 - GNE版本 [e.g. 0.1.4]

**Comment by kingname** [comment]
请在`.extract()`方法中加上如下参数：

```python
body_xpath='//div[@class="TRS_Editor"]'
```
